name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    if: ${{ !github.event.created }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: create env file
        run: |
          touch .env
          echo DEVELOPMENT_URL=${{ secrets.DEVELOPMENT_URL }} >> .env
          echo DEVELOPMENT_CLIENT_ID=${{ secrets.DEVELOPMENT_CLIENT_ID }} >> .env
          echo DEVELOPMENT_CLIENT_USERNAME=${{ secrets.DEVELOPMENT_CLIENT_USERNAME }} >> .env
          echo DEVELOPMENT_CLIENT_PASSWORD=${{ secrets.DEVELOPMENT_CLIENT_PASSWORD }} >> .env
          echo PRODUCTION_URL=${{ secrets.PRODUCTION_URL }} >> .env
          echo PRODUCTION_CLIENT_ID=${{ secrets.PRODUCTION_CLIENT_ID }} >> .env
          echo PRODUCTION_CLIENT_USERNAME=${{ secrets.PRODUCTION_CLIENT_USERNAME }} >> .env
          echo PRODUCTION_CLIENT_PASSWORD=${{ secrets.PRODUCTION_CLIENT_PASSWORD }} >> .env

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Making sure 'npm run lint' and 'npm run format' passes
        run: |
          yarn lint:check
          yarn format:check
